// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: calculator.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculatorClient interface {
	Add(ctx context.Context, in *ReqNums, opts ...grpc.CallOption) (*CalculResult, error)
	Minus(ctx context.Context, in *ReqNums, opts ...grpc.CallOption) (*CalculResult, error)
	Devide(ctx context.Context, in *ReqNums, opts ...grpc.CallOption) (*CalculResult, error)
	Multip(ctx context.Context, in *ReqNums, opts ...grpc.CallOption) (*CalculResult, error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Add(ctx context.Context, in *ReqNums, opts ...grpc.CallOption) (*CalculResult, error) {
	out := new(CalculResult)
	err := c.cc.Invoke(ctx, "/calculator.Calculator/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Minus(ctx context.Context, in *ReqNums, opts ...grpc.CallOption) (*CalculResult, error) {
	out := new(CalculResult)
	err := c.cc.Invoke(ctx, "/calculator.Calculator/Minus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Devide(ctx context.Context, in *ReqNums, opts ...grpc.CallOption) (*CalculResult, error) {
	out := new(CalculResult)
	err := c.cc.Invoke(ctx, "/calculator.Calculator/Devide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Multip(ctx context.Context, in *ReqNums, opts ...grpc.CallOption) (*CalculResult, error) {
	out := new(CalculResult)
	err := c.cc.Invoke(ctx, "/calculator.Calculator/Multip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServer is the server API for Calculator service.
// All implementations must embed UnimplementedCalculatorServer
// for forward compatibility
type CalculatorServer interface {
	Add(context.Context, *ReqNums) (*CalculResult, error)
	Minus(context.Context, *ReqNums) (*CalculResult, error)
	Devide(context.Context, *ReqNums) (*CalculResult, error)
	Multip(context.Context, *ReqNums) (*CalculResult, error)
	mustEmbedUnimplementedCalculatorServer()
}

// UnimplementedCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (UnimplementedCalculatorServer) Add(context.Context, *ReqNums) (*CalculResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedCalculatorServer) Minus(context.Context, *ReqNums) (*CalculResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Minus not implemented")
}
func (UnimplementedCalculatorServer) Devide(context.Context, *ReqNums) (*CalculResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Devide not implemented")
}
func (UnimplementedCalculatorServer) Multip(context.Context, *ReqNums) (*CalculResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multip not implemented")
}
func (UnimplementedCalculatorServer) mustEmbedUnimplementedCalculatorServer() {}

// UnsafeCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculatorServer will
// result in compilation errors.
type UnsafeCalculatorServer interface {
	mustEmbedUnimplementedCalculatorServer()
}

func RegisterCalculatorServer(s grpc.ServiceRegistrar, srv CalculatorServer) {
	s.RegisterService(&Calculator_ServiceDesc, srv)
}

func _Calculator_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNums)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.Calculator/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Add(ctx, req.(*ReqNums))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Minus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNums)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Minus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.Calculator/Minus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Minus(ctx, req.(*ReqNums))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Devide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNums)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Devide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.Calculator/Devide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Devide(ctx, req.(*ReqNums))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Multip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNums)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Multip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.Calculator/Multip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Multip(ctx, req.(*ReqNums))
	}
	return interceptor(ctx, in, info, handler)
}

// Calculator_ServiceDesc is the grpc.ServiceDesc for Calculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Calculator_Add_Handler,
		},
		{
			MethodName: "Minus",
			Handler:    _Calculator_Minus_Handler,
		},
		{
			MethodName: "Devide",
			Handler:    _Calculator_Devide_Handler,
		},
		{
			MethodName: "Multip",
			Handler:    _Calculator_Multip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator.proto",
}
